version: '3'

services:
  webserver:
    build:
      dockerfile: Dockerfile
      context: ./.docker
    privileged: true
    extra_hosts:
      - db.openbook:172.16.16.2
    volumes:
     - ./:/opt/openbook-api
    ports:
      - 80
      - 443
    working_dir: /opt/openbook-api
    networks:
      openbook:
        ipv4_address: 172.16.16.1
  db:
    image: mariadb:10.4.5
    hostname: db.openbook
    volumes:
     - mariadb:/var/lib/mysql
    ports:
      - 3306
    privileged: false
    environment:
      - MYSQL_ROOT_PASSWORD=openbook
      - MYSQL_DATABASE=openbook
    networks:
      openbook:
        ipv4_address: 172.16.16.2

volumes:
  mariadb:

networks:
  openbook:
    ipam:
      driver: default
      config:
        - subnet: "172.16.16.0/16"